print("ejemplo de listas")
arcoiris=["verde", "azul", "rosa", "rojo", "morado"]
print(arcoiris)
longitud=len(arcoiris)
print(longitud)
print("elementos que contiene la lista arcoiris ", longitud)
print(f"elementos que contiene la lista arcoiris v2 {longitud}")
print("accediendo a un elemento de la lista")
print(arcoiris[1])
print(f"elemento en la posicion 0 es {arcoiris[0]}")
print("agregar un elemento de la lista")
print(arcoiris)
arcoiris.append("naranja")
print(arcoiris)